# Generated by Django 4.2.2 on 2023-06-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='priceTour',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
